### ISSUE TITLE
Escaped characters are reconised correctly, but not unescaped when parsing

### ISSUE THREAD

**Issue by ohad** [alexhumphreys/idrall#89]
# To reproduce
```idris
import Idrall.Expr
import Idrall.ParserNew

foo : String
foo = case parseExprNew #""\\""# of
  Right (ETextLit _ $ MkChunks [] x, _) => x
  _ => "nothing"

main : IO ()
main = putStrLn foo
```
# Expected behaviour
Prints `\` since the input was a single escaped `\`.

# Actual behaviour
Prints `\\`.

**Comment by ohad** [comment]
I think the issue is here:
https://github.com/alexhumphreys/idrall/blob/346efac09ba197948410f3ddd42ac524f65fe7b8/Idrall/Parser/Lexer.idr#L320

While we correctly recognise that the characters are escaped correctly, the tokenizer immediately returns the string without change. Instead, it should unescape it correctly.

**Comment by gallais** [comment]
For the record we noticed that in Idris there's this function doing additional cleaning up
of the tokens in the basic `Rules` that involve string literals:

https://github.com/idris-lang/Idris2/blob/main/src/Parser/Support.idr#L130
